[webservers]
web1 ansible_host=127.0.0.1 ansible_port=2221
web2 ansible_host=127.0.0.1 ansible_port=2222
web3 ansible_host=127.0.0.1 ansible_port=2223

[webservers:vars]
ansible_user=deploy
ansible_ssh_private_key_file=./docker/ansible_lab_key
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become_pass="{{ vault_deploy_sudo_pass }}"
