services:
  web1:
    build:
      context: .
      args:
        DEPLOY_PASSWORD: ${DEPLOY_PASSWORD}
    container_name: ansible-web1
    hostname: web1
    ports:
      - "127.0.0.1:2221:22"
    networks:
      - ansible-lab

  web2:
    build:
      context: .
      args:
        DEPLOY_PASSWORD: ${DEPLOY_PASSWORD}
    container_name: ansible-web2
    hostname: web2
    ports:
      - "127.0.0.1:2222:22"
    networks:
      - ansible-lab

  web3:
    build:
      context: .
      args:
        DEPLOY_PASSWORD: ${DEPLOY_PASSWORD}
    container_name: ansible-web3
    hostname: web3
    ports:
      - "127.0.0.1:2223:22"
    networks:
      - ansible-lab

networks:
  ansible-lab:
    driver: bridge
